### ISSUE TITLE
java.lang.nullpointerexception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TuononenP/pkg-config-support-for-eclipse-cdt#16]
```
when i want to select (gtk+-3 and cairo) in pkg config and apply it gave me 
this error:java.lang.nullpointerexception
what should i do?
```

Original issue reported on code.google.com by `royaslt...@gmail.com` on 5 Jun 2014 at 6:30

Attachments:
- [Captureec.JPG](https://storage.googleapis.com/google-code-attachments/pkg-config-support-for-eclipse-cdt/issue-16/comment-0/Captureec.JPG)

**Comment by TuononenP** [comment]
Fixed this in the latest version I uploaded today in update site. Also fixed Eclipse marketplace installation. Tested with Eclipse Neon.
