### ISSUE TITLE
Truncated include path

### ISSUE THREAD

**Issue by PengZheng** [TuononenP/pkg-config-support-for-eclipse-cdt#18]
$ pkg-config --cflags sofia-sip-ua
-I/usr/include/sofia-sip-1.12

while the plugin(1.0.0.201511082105) gives '-I/usr/include/sofia-sip-1.1'

**Comment by JonathanIliasPillet** [comment]
I have the same issue with Eclipse Mars.
I don't know if it's related, but "defines" are also omitted but this was working with an old version of pkg-config on Eclipse Kepler.

**Comment by Linwood-F** [comment]
I think I may be having this as well.  Apologies as I am new to eclipse as well, but on Neon 4.6.1 and the pkg-config package I pulled today (1.0.0.201511082105) when selecting GTK+-3.0 the very last item in the path as seen when running pkg-config manually shows 

 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include

But I get a warning in eclipse 

Invalid project path: Include path not found (/usr/lib/x86_64-linux-gnu/glib-2.0/includ).

Note the missing e on the end.  It did work mostly as the other GTK path related errors are now gone.

**Comment by collegedude** [comment]
I have the same problem since I have updated from Mars to Neon

**Comment by sheldonrobinson** [comment]
Submitted fix, see pull request  #19

**Comment by TuononenP** [comment]
Merged.
