### ISSUE TITLE
Support for Eclipse 4.2 Juno

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TuononenP/pkg-config-support-for-eclipse-cdt#8]
```
This plugin works nicely on Eclipse 3.7 but it doesn't work on Eclipse 4.2. It 
would be nice to support this version also.

```

Original issue reported on code.google.com by `lmedi...@gmail.com` on 19 Jun 2012 at 8:31

**Comment by TuononenP** [comment]
I'm closing this now. The latest version of the plugin should work with Eclipse Neon 4.6.
